/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Shape, Size } from "./components/types";
export { Shape, Size } from "./components/types";
export namespace Components {
    interface DidroomAvatar {
        "name"?: string;
        "shape"?: Shape;
        "size"?: Size;
        "src"?: string;
    }
}
declare global {
    interface HTMLDidroomAvatarElement extends Components.DidroomAvatar, HTMLStencilElement {
    }
    var HTMLDidroomAvatarElement: {
        prototype: HTMLDidroomAvatarElement;
        new (): HTMLDidroomAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "didroom-avatar": HTMLDidroomAvatarElement;
    }
}
declare namespace LocalJSX {
    interface DidroomAvatar {
        "name"?: string;
        "shape"?: Shape;
        "size"?: Size;
        "src"?: string;
    }
    interface IntrinsicElements {
        "didroom-avatar": DidroomAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "didroom-avatar": LocalJSX.DidroomAvatar & JSXBase.HTMLAttributes<HTMLDidroomAvatarElement>;
        }
    }
}
